### ISSUE TITLE
Security Data Issues - Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [vertx-web-site/vertx-web-site.github.io#1]
Hi ,

url : https://github.com/vertx-web-site/vertx-web-site.github.io/tree/aeccb4f61d42059695068c196752e67d8e7a8252/_next/data/_aW2gNXNcvrAiM1F4iFFa/docs/3.9.1/vertx-auth-jwt

BEGIN PRIVATE KEY-

have commit that need to remove from the github history
attacker can see it and use it ...

encrypt your secrets !!!!

Our Bug Help you to be more Secure and protect your data ?
Buy me a coffee (or more likely a beer)
https://www.buymeacoffee.com/bugbounty
☕☕☕☕☕

**Comment by michel-kraemer** [comment]
This is deliberate. See here:
https://vertx.io/docs/vertx-auth-jwt/java/
