### ISSUE TITLE
Imprint deployed vertx-web-site hash commit in web-site markup

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#109]
We should imprint the hash of the deployed site commit in the generated site markup.

This allows to know precisely which commit of the web-site repository is hosted.

**Comment by michel-kraemer** [comment]
The feature has been implemented and is live. Just open your browser console to see the embedded information:

![image](https://user-images.githubusercontent.com/295407/118620761-180f5e00-b7c6-11eb-8033-37c34fd75053.png)
