### ISSUE TITLE
Add link to translation of vert.x website

### ISSUE THREAD

**Issue by Leibnizhu** [vertx-web-site/vertx-web-site.github.io#114]
Hello @vietj  :
  We are the Vert.x user group of China (https://github.com/vertx-china).  
  We forked this repository and translated it into Chinese(https://vertx-china.github.io/), including  vert.x document (https://vertx-china.github.io/docs/) , and now it's finished.   
  In the future, we will continue to update the translation as Vert.x is updated. So we hope to add a link to our translated website on the official website (https://vertx.io/), so that Chinese users could learn and use Vert.x more easily.

**Comment by vietj** [comment]
sorry I overlooked this issue, we will discuss this with other committers and  get back to you
