### ISSUE TITLE
API docs missing

### ISSUE THREAD

**Issue by Torjas** [vertx-web-site/vertx-web-site.github.io#119]
Hi,

The API link on the [vert.x docs page](https://vertx.io/docs/) points to https://vertx.io/docs/apidocs, which throws a 404 error.

**Comment by michel-kraemer** [comment]
Thanks for spotting this. I will fix it later today.

**Comment by michel-kraemer** [comment]
Until then, you can use this link:
https://vertx.io/docs/4.2.1/apidocs/

**Comment by michel-kraemer** [comment]
Fixed in f8642b0
