### ISSUE TITLE
Wrong snapshot repository

### ISSUE THREAD

**Issue by cescoffier** [vertx-web-site/vertx-web-site.github.io#125]
If should be updated to:

```
<repository>
      <id>sonatype-s01-snapshots</id>
      <url>https://s01.oss.sonatype.org/content/repositories/snapshots</url>
      <snapshots>
          <enabled>true</enabled>
      </snapshots>
 </repository>
```

**Comment by michel-kraemer** [comment]
Hi @cescoffier! What do you mean exactly? Can you point me to a page/file?

**Comment by cescoffier** [comment]
Hi @michel-kraemer 
I know it's an old page, but here: https://vertx.io/download/.

On the new web site, the correct snapshot repository should be mentioned somewhere.
