### ISSUE TITLE
vertx web deployed in spring boot, static resource can't be found in spring boot jar

### ISSUE THREAD

**Issue by don9139** [vertx-web-site/vertx-web-site.github.io#127]
Questions
deployed vertx web in spring boot, review the static resource in vertx webroot, it can't be found with 404 error.

Version
vertx.version > 4.0.0

Context
I encountered an exception which looks suspicious while ...

Do you have a reproducer?
springboot jar can be uploaded.

Link to github project/gist
Steps to reproduce
java -jar ./test-vertx.jar
open web brower and input localhost:8080/hello.txt
Extra
JVM version 1.8

**Comment by don9139** [comment]
Resource not found

**Comment by don9139** [comment]
[test-vertx.jar.zip](https://github.com/vertx-web-site/vertx-web-site/files/8686038/test-vertx.jar.zip)

**Comment by don9139** [comment]
there is no issue when vertx version < 4.0.0

**Comment by don9139** [comment]
it should be the issue from class
io.vertx.ext.web.handler.impl.StaticHandlerImpl

**Comment by don9139** [comment]
it should be the issue from class
io.vertx.ext.web.handler.impl.StaticHandlerImpl

**Comment by don9139** [comment]
it should be the issue from class
io.vertx.ext.web.handler.impl.StaticHandlerImpl

**Comment by don9139** [comment]
it should be the issue from class
io.vertx.ext.web.handler.impl.StaticHandlerImpl

**Comment by michel-kraemer** [comment]
This is the repository for the Vert.x website. If you have a question regarding Vert.x itself or one of its components (other than the website), please use the support channels:
https://vertx.io/channels/
