### ISSUE TITLE
Website serve some http contents

### ISSUE THREAD

**Issue by eclipsewebmaster** [vertx-web-site/vertx-web-site.github.io#132]
There is a plain http redirection when trying to reach out to `www.vertx.io`: 

https://www.vertx.io:443 `--301-->` **http://vertx.io:80/** `--301-->` https://vertx.io:443/

There must be a misconfiguration somewhere. This can lead to error or warning messages in some browsers.

**Comment by michel-kraemer** [comment]
@vietj Can you take care of that please? I don't have access to the domain configuration in Cloudflare.

**Comment by eclipsewebmaster** [comment]
Hello, we would like to move this forward but are incapable of doing so. @vietj how can we help get this setting changed?

**Comment by vietj** [comment]
I will take care of this soon. I have been pinged directly.

**Comment by vietj** [comment]
it should work fine now, sorry I missed this notification issue.
