### ISSUE TITLE
CloudFlare configuration: minimum TLS version 1.2 and HTTPS always

### ISSUE THREAD

**Issue by eclipsewebmaster** [vertx-web-site/vertx-web-site.github.io#133]
Hello,

New security policies at the Eclipse Foundation require TLS minimum version 1.2 and HTTPS only. As you appear to be using your own CloudFlare account, please configure the minimum TLS version to 1.2 and enable "Always use HTTPS"

https://developers.cloudflare.com/ssl/edge-certificates/additional-options/minimum-tls/

**Comment by michel-kraemer** [comment]
@vietj I think this is related to #132. Can you please take care of it? I don't have access to the Cloudflare account.

**Comment by eclipsewebmaster** [comment]
Yes, they are related. Thanks.

**Comment by eclipsewebmaster** [comment]
The EF IT team is willing to help, but I don't believe we have credentials to this CloudFlare account.

**Comment by eclipsewebmaster** [comment]
Hello, we would like to move this forward but are incapable of doing so. @vietj how can we help get this setting changed?

**Comment by vietj** [comment]
it should be good now
