### ISSUE TITLE
PgClient: Please use permalink to Postgres docs

### ISSUE THREAD

**Issue by matthudsonatx** [vertx-web-site/vertx-web-site.github.io#136]
Location: https://vertx.io/docs/vertx-pg-client/java/#_configuration

"You can refer to the [official documentation](https://www.postgresql.org/docs/9.6/static/libpq-envars.html) for more details"

should instead link: [official documentation](https://www.postgresql.org/docs/current/libpq-envars.html)

**Comment by michel-kraemer** [comment]
Thanks for reporting this. The docs are generated from the Asciidoc source files in the respective repository. The file you are referring to is here:
https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/asciidoc/index.adoc
Can you please open an issue there? Thanks!
