### ISSUE TITLE
Improving metadata for blog posts

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#158]
I've shared a blog post today and, when sharing it on social media, found that the chosen illustration was my GitHub profile picture.

LinkedIn has a tool which allows to analyze a link shared in a post:

https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fvertx.io%2Fblog%2Fmicrometer-metrics-performance%2F

It confirms the author's GH profile pic is the identified image and that the website general description is associated with the article.

@michel-kraemer do you know if our blogging tool allows to improve this?

**Comment by michel-kraemer** [comment]
Yes, this is possible. I have code that I could reuse.

What information do you want to display? Something like the following would be easy to implement:

![image](https://github.com/vertx-web-site/vertx-web-site.github.io/assets/295407/7ae64cd9-0a2f-4c7d-959a-b2c51bf9c967)

**Comment by michel-kraemer** [comment]
(This is an example from my website, by the way)

**Comment by tsegismont** [comment]
How did you get this image? It looks great (title + date + description of the article).

Is it generated automatically by LinkedIn, Twitter ... etc when pasting a link in the compose panel?

Is is possible to choose an alternative image? For example, I wanted to have one of the flamegraphs in the article instead of my GH profile pic

**Comment by michel-kraemer** [comment]
My website uses automatically generated [Open Graph metadata](https://ogp.me/) from which the LinkedIn tool gets its information. The image is in the `og:image` tag, which is generated during the build process.

Yes, it would be possible to embed custom graphics in the generated image. How soon do you need a solution? If you just want to set a custom image, I can quickly hack something tonight. Just send me the image. For a clean solution, I could try to find some time over the weekend or during next week.

**Comment by tsegismont** [comment]
There's no hurry, really. Thank you for taking time to help us again :hugs:

**Comment by michel-kraemer** [comment]
Ah. OK. Then I'll implement it some time next week.

**Comment by michel-kraemer** [comment]
@tsegismont OpenGraph images for blog posts are now generated during build. Your post, for example, looks like this:

![micrometer-metrics-performance](https://github.com/vertx-web-site/vertx-web-site.github.io/assets/295407/334ec5a4-3d4e-45a9-9c74-c7637d721b38)

**Comment by tsegismont** [comment]
Excellent @michel-kraemer ! And it seems it's already been picked-up by LinkedIn :100:
