### ISSUE TITLE
Hidden documentation

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#167]
We would like to have documentation that is still present and processed on the web-site but that does not appear in the new left navigation. This should be used for module that are sunsetting, e.g. like vertx-service-discovery, we still want documentation to exist but we don't want to link to it.

e.g. a "hidden" field in the json doc metadata

**Comment by michel-kraemer** [comment]
You can now set the `hidden` field to `true` to hide a module.
