### ISSUE TITLE
Make all documentation headers clickable

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#168]
In the previous version of the website, all documentation headers were clickable, making it easy to copy an anchor link, like:

https://vertx.io/docs/vertx-hazelcast/java/#_using_lite_members

**Comment by michel-kraemer** [comment]
How about clicking on the item in the right sidebar? Would that be enough?

**Comment by tsegismont** [comment]
Clicking on the item in the right sidebar already works, if the section level is between 1 and 3 (tbc). But if the section you want to link to is nested at a lower level, it doesn't appear on the right sidebar (for good reasons).

**Comment by tsegismont** [comment]
Awesome @michel-kraemer , thank you!
