### ISSUE TITLE
Javadoc is not working

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#19]
I got a 404 when clicking on a JavaDoc link from a doc (e.g in vertx-core).

**Comment by vietj** [comment]
@michel-kraemer any progress on this ?

**Comment by michel-kraemer** [comment]
Yes. It is working locally already. I will push a commit later today.

**Comment by michel-kraemer** [comment]
There is something wrong with the deployment (https://github.com/vertx-web-site/vertx-web-site.github.io). The whole `docs` folder is missing now. I'm investigating...

**Comment by vietj** [comment]
thanks.

I pushed an update of the main docs page to ref docs.

There are some small issues, like

- the Auth section is a bit long
- some icons might not be the best choice

**Comment by michel-kraemer** [comment]
OK. I'll have a look.

The docs should now work again. At least the `docs` folder is there now, but it seems GitHub has still cached the 404, so we need to wait until they perform a refresh.

Anyhow, you can test it locally. You need to run `npm run update-docs` once so the API docs are copied to the correct folder.

**Comment by vietj** [comment]
I think I broke the build when pushing the docs because I imported an icon that was not used and that broke the build in actions (but working fine locally)

**Comment by michel-kraemer** [comment]
You can run `npm run lint` before pushing to check if you fixed all errors/warnings.

**Comment by vietj** [comment]
ok, I will add this to the README file

**Comment by vietj** [comment]
how can I run it with docker ?

**Comment by vietj** [comment]
I'm for now mostly using Docker, but perhaps I can simply use a shell in docker

**Comment by vietj** [comment]
it does work now that site was redeployed https://vertx-web-site.github.io/docs/apidocs/io/vertx/core/DeploymentOptions.html#setWorker-boolean-

**Comment by vietj** [comment]
I think we are good to go soon, besides the docs page improvements but I think it's not blocking

**Comment by michel-kraemer** [comment]
> how can I run it with docker ?

The dockerfile runs `npm run build` which itself runs `npm run lint` so everything should be covered 🤷‍♂️

**Comment by vietj** [comment]
ok, I think it is because I added those incrementally and I should have perhaps quit and done a full build before committing ?

**Comment by michel-kraemer** [comment]
Yes. That would have helped.

By the way, you should also see warnings in the terminal (even in dev mode). But here they're just warnings and don't prevent the build.
