### ISSUE TITLE
Font family different than the howtos website

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#20]
We have made significant progress on the website design. Before it's too late (taking too much time to change), we need to decided whether or not to use the same font family on both the howtos and the main websites.

**Comment by jponge** [comment]
I think we decided to stay on the font chosen by @michel-kraemer 

Should we change that of the how-tos?

**Comment by tsegismont** [comment]
@jponge we didn't decide anything during the last meeting. Actually I filed this issue upon @vietj 's request to start the conversation. Has this been discussed in a previous meeting I didn't attend?

I believe we should use the same font family on both websites. I'm fine with changing the howtos font if it's easier.

**Comment by michel-kraemer** [comment]
> I believe we should use the same font family on both websites. I'm fine with changing the howtos font if it's easier.

That would be my recommendation. It's a lot easier because changing the font essentially changes the whole design.

**Comment by jponge** [comment]
I can have a look at the howtos.

**Comment by jponge** [comment]
Done, expect the pages to converge to the new theme as Travis cron builds happen.
