### ISSUE TITLE
Clickable headings

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#22]
Very often when answering community questions, I point users to special sections of the documentation.

It would be great if headings were clickable so that we can just copy/paste the url from the browser bar.

**Comment by michel-kraemer** [comment]
This should be possible in Asciidoctor.js with the `sectanchors` and `sectlinks` attributes. As an alternative, you can always click on the heading in the TOC on the left and then copy the link from the address bar.

What do the others think about this feature? @jponge @vietj @slinkydeveloper @pmlopes Should I implement it?

**Comment by tsegismont** [comment]
Actually I thought about headings from the website own content (Markdown),
not the docs content.

Le jeu. 11 juin 2020 à 15:53, Michel Krämer <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
Also, there are a lot of subheadings that have ids but are not in the TOC

Le jeu. 11 juin 2020 à 16:23, Thomas SEGISMONT <tsegismont@gmail.com> a
écrit :

**Comment by pmlopes** [comment]
I think all heading should have a static anchor, for example on core docs, the first one is "in the beginning there was vert.x" .

This doesn't need to be in the toc but having a simple anchor should sufice for link to docs, support, etc...

**Comment by tsegismont** [comment]
That's exactly what I mean Paulo 🎯

**Comment by michel-kraemer** [comment]
Based on our discussion today, I will add it to docs, blog, getting started page, and intro page for the time being (we can add more pages later if necessary)
