### ISSUE TITLE
Split of docs main page seems to not work for large lists

### ISSUE THREAD

**Issue by pmlopes** [vertx-web-site/vertx-web-site.github.io#23]
The section "auth" in https://github.com/vertx-web-site/vertx-web-site/blob/master/pages/docs/index.jsx#L118-L165 is quite large but unlike other sections, all it's sub entries seem to be formatted as 1 entry per row, not 2 or 3 entries per row.

**Comment by michel-kraemer** [comment]
Just fixed in master

**Comment by michel-kraemer** [comment]
I need to revise the design of the docs page anyhow. I think I will add headers for the sections again and a table of contents on the left hand side.
