### ISSUE TITLE
There's some asciidoc render issue with @

### ISSUE THREAD

**Issue by pmlopes** [vertx-web-site/vertx-web-site.github.io#29]
If you look into a code block that uses annotations, you see:

```
&#64;
```

instead of

```
@
```

**Comment by pmlopes** [comment]
Quick link to see the issue: https://vertx-web-site.github.io/docs/vertx-core/java/#_the_vert_x_launcher

**Comment by michel-kraemer** [comment]
I see the same issue here:
https://github.com/eclipse-vertx/vert.x/blob/master/src/main/asciidoc/index.adoc#the-vertx-launcher

Maybe it's an issue in the asciidoc source?

**Comment by michel-kraemer** [comment]
However, I see many `@literal` statements in the core docs. I don't think this is a valid asciidoc statement, but I might be mistaken.

**Comment by pmlopes** [comment]
Indeed, the current website does have the same result and es4x which uses pandoc to convert from asciidoc to markdown does the same.

I guess it's an issue with the docs themselves.
