### ISSUE TITLE
Too large side borders

### ISSUE THREAD

**Issue by slinkydeveloper** [vertx-web-site/vertx-web-site.github.io#44]
I'm on a 1920x1080 screen and the side border is far too big (at least 30/40% of the screen), I think we can use this space to read better the docs :smile:  

![Screenshot_2020-08-10 Vert x Core Eclipse Vert x](https://user-images.githubusercontent.com/6706544/89790720-a1e91700-db22-11ea-9c2e-a7dc04f60ebe.png)

**Comment by michel-kraemer** [comment]
Please be aware that the wider the text, the harder it is to read (i.e. the longer the lines, the harder it is for the eye to follow them). See also https://baymard.com/blog/line-length-readability That's the reason why (professional) websites typically use a rather narrow format for long texts.
