### ISSUE TITLE
FAQ large payloads/file uploads over the event bus

### ISSUE THREAD

**Issue by slinkydeveloper** [vertx-web-site/vertx-web-site.github.io#46]
There is a question about large payloads/file uploads over event bus which is asked quite often on SO and mailing lists, we should add an FAQ about that https://stackoverflow.com/questions/63706692/vertx-web-api-service-file-uploading-using-openapi3routerfactory-and-eventbus

**Comment by michel-kraemer** [comment]
@slinkydeveloper Can you provide a pull request for the FAQ entry?
