### ISSUE TITLE
Some documentation pages do not have titles

### ISSUE THREAD

**Issue by michel-kraemer** [vertx-web-site/vertx-web-site.github.io#49]
I noticed that some pages don't have titles.

For example: https://vertx-web-site.github.io/docs/vertx-auth-sql-client/java/
"SQL Client Auth Provider implementation" is on the second level (`<h2>`).

The same applies to https://vertx-web-site.github.io/docs/vertx-auth-htdigest/java/ and others.

Can someone please consolidate the AsciiDoc files?

**Comment by pmlopes** [comment]
I've reviewed all auth docs, (all suffered from the same issue start with `h2`). They should be all ok on the master branch

**Comment by tsegismont** [comment]
Michel, have you spotted any other doc than auth with this problem? Which
ones?
Otherwise, is there a way to find which one quickly (eg by running a build
and grep a specific warning)?

**Comment by michel-kraemer** [comment]
Thanks for fixing the auth docs, Paulo! I also spotted this one:
https://vertx-web-site.github.io/docs/vertx-circuit-breaker/java/

The rest seems to be OK. I just went through all pages.

**Comment by tsegismont** [comment]
Thanks Michel, I'll take care of it

Le mer. 30 sept. 2020 à 16:51, Michel Krämer <notifications@github.com> a
écrit :

**Comment by tsegismont** [comment]
@michel-kraemer the circuit-breaker doc is fixed

**Comment by michel-kraemer** [comment]
Now that 4.0.0.CR1 has been released, I checked all titles again and they're all OK.
