### ISSUE TITLE
Configurable version selector

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#61]
When you browse to documentation for a module that exist only in the 4.x stack (e.g [SQL Client Templates](https://vertx-web-site.github.io/docs/vertx-sql-client-templates/java/)), the version selector still indicate all known versions.

If this selector is configurable, we could filter out versions that do not include the current module.

Is that doable @michel-kraemer ?

**Comment by michel-kraemer** [comment]
Very good point. This can be implemented. I will assign this issue to me.

**Comment by tsegismont** [comment]
Thank you Michel!
