### ISSUE TITLE
Vert.x 4 web-site missing pages

### ISSUE THREAD

**Issue by vietj** [vertx-web-site/vertx-web-site.github.io#69]
A few pages are missing and lead to 404.

While we don't want to have these pages linked on the web-site, they should be still on the new web-site

- https://vertx-web-site.github.io/download/
- https://vertx-web-site.github.io/materials/
- a few recents blog pages

**Comment by vietj** [comment]
assigned to you @michel-kraemer the page are done and should have only a few minor modification in the future (with Docker)

**Comment by michel-kraemer** [comment]
Closed in 881e1f2608f9e986fe8b648923cabf14567a9ebb
