### ISSUE TITLE
Http and Curl output in Getting started page

### ISSUE THREAD

**Issue by slinkydeveloper** [vertx-web-site/vertx-web-site.github.io#8]
From https://github.com/vertx-web-site/vertx-web-site/pull/1#issuecomment-615093787

@michel-kraemer any inputs on this?

**Comment by michel-kraemer** [comment]
This should be no problem. We could add tabs for curl and httpie.

**Comment by slinkydeveloper** [comment]
Can you give me an help with the tabs?

**Comment by michel-kraemer** [comment]
Sure. That's what I meant ;) Just add the additional code to the page and I'll do the rest.
