### ISSUE TITLE
A broken link in the `RxJava interoperability documentation` section (in `vertx-lang-kotlin-coroutines` doc page)

### ISSUE THREAD

**Issue by jtonic** [vertx-web-site/vertx-web-site.github.io#85]
The link Guide to reactive streams with coroutines in the RxJava interoperability is broken.

Doc link: https://vertx.io/docs/vertx-lang-kotlin-coroutines/kotlin/#_rxjava_interoperability 
Broken link: RxJava interoperability 
Version: 4.0.0

**Comment by tsegismont** [comment]
@jtonic thanks for reporting it.

**Comment by tsegismont** [comment]
Closed in https://github.com/vert-x3/vertx-lang-kotlin/commit/2541c409b8561ebdab90ea0109f75269c17d2534 and https://github.com/vert-x3/vertx-lang-kotlin/commit/9307474b914d17489952a7acee81ba6584a40a7e
