### ISSUE TITLE
Vertx 4 docs refer to 4.0.1-SNAPSHOT instead of 4.0.0

### ISSUE THREAD

**Issue by tsegismont** [vertx-web-site/vertx-web-site.github.io#89]
A couple examples:

https://vertx.io/docs/vertx-web/java/#_using_vert_x_web

https://vertx.io/docs/vertx-infinispan/java/#_using_this_cluster_manager

**Comment by vietj** [comment]
that is temporary because we needed it to have Kotlin and Groovy docs. This will be resolved for 4.0.1 release

**Comment by tsegismont** [comment]
Resolved with the 4.0.2 release
