### ISSUE TITLE
search seems not to be working because apidocs.json is missing

### ISSUE THREAD

**Issue by pmlopes** [vertx-web-site/vertx-web-site.github.io#93]
My browser tries to fetch: https://vertx.io/_next/data/krWJfm3kCQWwU0tFgSN4W/docs/apidocs.json

Which is currently missing 404.

Same behavior when using incognito mode.

**Comment by michel-kraemer** [comment]
I wasn't able to reproduce the issue. I tried it with four different browsers in normal mode and private mode.

Nevertheless, I was able to fix the error regarding the missing apidocs.json file. Can you try again and see if it works now?

**Comment by pmlopes** [comment]
Seems to be working for me again:
![image](https://user-images.githubusercontent.com/849467/107359271-c8d5d500-6ad4-11eb-929a-cf8735c7789e.png)
